=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/plante_TextViz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  créé le ?? -->
<!--  modifié le 1 décembre 2011 -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="fiche">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="description">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="taxon">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeTaxon" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="parent">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeParent" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="contenu">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="paragraphe">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element minOccurs="0" name="titre" nillable="false" type="xsd:string"/>
                          <xsd:element name="alinea" nillable="false" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element minOccurs="0" name="maladies">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="maladie">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="nom_maladie" nillable="false" type="xsd:string"
                            maxOccurs="1"/>
                          <xsd:element name="enonce" nillable="false" type="xsd:string"/>
                          <xsd:element maxOccurs="1" minOccurs="0" name="photos_maladie">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element maxOccurs="unbounded" name="fichier_photo_maladie"
                                  type="xsd:string"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element maxOccurs="1" minOccurs="0" name="photos_plante">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="photo_plante">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="titre_photo" nillable="false" type="xsd:string"
                            maxOccurs="1"/>
                          <xsd:element name="fichier_photo_plante" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="classeVilmorin">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeClasseVilmorin" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="typeTaxon">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="genre"/>
      <xsd:enumeration value="espece"/>
      <xsd:enumeration value="variete"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="typeParent">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="famille"/>
      <xsd:enumeration value="genre"/>
      <xsd:enumeration value="espece"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="typeClasseVilmorin">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="arbre"/>
      <xsd:enumeration value="fleur"/>
      <xsd:enumeration value="arbuste"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/Brodiaea1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
    <description>
        <taxon type="espece">Brodiaea laxa</taxon>
        <parent type = "genre">Brodiaea</parent>
        <contenu>
            <paragraphe>
                <titre>ADONE, ANNUELLE</titre>
                <alinea>
                    Plante à feuilles étroites et rubanées. Fleurs en forme d'étoile, groupées au sommet de tiges dressées de 40 à 50 cm.
                </alinea>
            </paragraphe>
            <paragraphe>
               <titre>Attrait / Intérêt</titre>
                <alinea>
                    floraison printanière d'avril à juin.
                </alinea>
            </paragraphe>
            <paragraphe>
               <titre>Sol / Exposition</titre>
                <alinea>
                    sols sains, frais, en situation ensoleillée, abritée. Redoute les hivers très rigoureux.
                </alinea>
            </paragraphe>
            <paragraphe>
               <titre>Culture</titre>
                <alinea>
                    plantez les bulbes de septembre à décembre, à 6 ou 8 cm de profondeur et à 15cm d'écartement. Dans les régions à hivers rigoureux, couvrir le sol de paille ou de feuilles mortes. Il est préférable de laisser les bulbes en place pendant plusieurs années. Ils formeront de très belles touffes.
                </alinea>
            </paragraphe>
            <paragraphe>
               <titre>Utilisation</titre>
                 <alinea>
                     massifs, plates-bandes, rocailles. Fleurs coupées. Culture en pot possible.
                 </alinea>
             </paragraphe>
        </contenu>

    <classeVilmorin type= "fleur"/>
        </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/PHACELIE_A_FEUILLES_DETANAISIE1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Phacelia tanacetifolia</taxon>
    <parent type="genre">Phacélie</parent>
    <contenu>
      <paragraphe>
        <titre>PHACELIE A FEUILLES DETANAISIE</titre>
        <alinea> Plante de 40 à 60 cm de hauteur, à fleurs bleu clair, légèrement grisâtres, groupées en longues grappes roulées en dehors et se redressant en s'allongeant à mesure que la floraison s'effectue.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Culture</titre>
        <alinea>semez clair en place en avril, la phacélie ne supportant pas la transplantation.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Utilisation</titre>
        <alinea>le port trapu de la Phacelia campanularia la destine tout spécialement à la plantation en pots qui permet d'admirer de près le bleu splendide des fleurs. Le Phacelia tanacetifolia, de moindre intérêt ornemental, est surtout cultivé en tant que plante mellifère car il est très apprécié des abeilles.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Phacélie à feuilles de Tanaisie</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/LIS_LONGIFLORUM1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Lilium longiflorum </taxon>
    <parent type="genre">Lilium</parent>
    <contenu>
      <paragraphe>
        <titre>LIS LONGIFLORUM</titre>
        <alinea>Haut de 60 à 90 cm, il donne en juin-juillet trois fleurs et plus, en tube allongé, horizontales, très odorantes. C'est le très beau lis en cornet des fleuristes. Bien que non rustique et ne faisant pas partie des lis de jardin, il méritait d'être mentionné.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Lis longiflorum</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/CISTE_ALBIDUS1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Cistus albidus</taxon>
    <parent type="genre">Cistus</parent>
    <contenu>
      <paragraphe>
        <titre>CISTE ALBIDUS</titre>
        <alinea> Hauteur 1,50 à 2 m. Feuilles duveteuses, argentées. Fleurs rose pâle.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante />
    <classeVilmorin type="arbuste" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/CAESALPINIA_CADUC1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Caesalpinia gilliesii = Poinciana</taxon>
    <parent type="genre">Caesalpinia</parent>
    <contenu>
      <paragraphe>
        <titre>CAESALPINIA CADUC</titre>
	<alinea>Oiseau de Paradis. Fleurit en juillet-août. Peu rustique.
Hauteur: 1,50 à 2,50m. Charmant arbuste du Midi et du littoral atlantique, dense, mais d'aspect léger grâce à ses grandes feuilles bipennées à nombreuses folioles étroites.
Les fleurs, groupées par 30 ou 40 en panicules terminales, sont jaune vif avec un
bouquet d'étamines rouges, très saillantes, qui justifient son nom commun d'oiseau de
paradis. Ce bel arbuste doit être planté en isolé le long d'un mur ensoleillé, en terre
légère, bien drainée.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Caesalpinia gilliesii</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="arbuste" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/PHYSOSTEGIA_VIVACE0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Physostegia</taxon>
    <parent type="famille">Labiac√©es</parent>
    <contenu>
      <paragraphe>
        <titre>PHYSOSTEGIA VIVACE</titre>
        <alinea />
      </paragraphe>
    </contenu>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/Polypodium0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
    <description>
        <taxon type="genre">Polypodium</taxon>
        <parent type = "famille">Polypodiaceae</parent>
        <contenu>
            <paragraphe>
                <titre>Polypodium</titre>
                <alinea>

                </alinea>
            </paragraphe>
        </contenu>
    <classeVilmorin type= "fleur"/>
    </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/JACINTHE_DU_CAP0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Galtonia candicans</taxon>
    <parent type="famille">Liliac√©es</parent>
    <contenu>
      <paragraphe>
        <titre>JACINTHE DU CAP</titre>
        <alinea />
      </paragraphe>
    </contenu>
    <classeVilmorin type="fleur" />
  </description>
</fiche>
