=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/plante_TextViz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  créé le ?? -->
<!--  modifié le 1 décembre 2011 -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="fiche">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="description">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="taxon">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeTaxon" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="parent">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeParent" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="contenu">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="paragraphe">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element minOccurs="0" name="titre" nillable="false" type="xsd:string"/>
                          <xsd:element name="alinea" nillable="false" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element minOccurs="0" name="maladies">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="maladie">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="nom_maladie" nillable="false" type="xsd:string"
                            maxOccurs="1"/>
                          <xsd:element name="enonce" nillable="false" type="xsd:string"/>
                          <xsd:element maxOccurs="1" minOccurs="0" name="photos_maladie">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element maxOccurs="unbounded" name="fichier_photo_maladie"
                                  type="xsd:string"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element maxOccurs="1" minOccurs="0" name="photos_plante">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="photo_plante">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="titre_photo" nillable="false" type="xsd:string"
                            maxOccurs="1"/>
                          <xsd:element name="fichier_photo_plante" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="classeVilmorin">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeClasseVilmorin" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="typeTaxon">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="genre"/>
      <xsd:enumeration value="espece"/>
      <xsd:enumeration value="variete"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="typeParent">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="famille"/>
      <xsd:enumeration value="genre"/>
      <xsd:enumeration value="espece"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="typeClasseVilmorin">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="arbre"/>
      <xsd:enumeration value="fleur"/>
      <xsd:enumeration value="arbuste"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/Ancolie3.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
    <description>
        <taxon type="espece">Aquilegia coerulea hybride</taxon>
        <parent type = "genre">Aquilegia</parent>
        <contenu>
            <paragraphe>
                <titre>ANCOLIE HYBRIDE DECOERULEA</titre>
                <alinea>
                    Fleur simple avec de longs éperons, possédant la grande élégance de l'ancolie dorée (ancolie chrysantha) dont elle est issue. Elle offre une gamme très riche de coloris. 
                </alinea>
            </paragraphe>
        </contenu>

    <classeVilmorin type= "fleur"/>
        </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/HERBE_DE_LA_PAMPA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Cortaderia selloana</taxon>
    <parent type="genre">GRAMINEES ORNEMENTALES</parent>
    <contenu>
      <paragraphe>
        <titre>HERBE DE LA PAMPA</titre>
        <alinea> Cette graminée géante forme de très fortes touffes vivaces, aux feuilles longues et étroites, dentées et très coupantes, d'où partent, à l'automne, de longues inflorescences pouvant atteindre 3 mètres, portant à leur extrémité un long panache argenté et soyeux, de 60 à 80 cm de longueur. Cette magnifique herbe de la Pampa originaire d'Amérique du Sud comporte des variétés de taille plus ou moins élevée dont une produit des panaches rosés. Elle possède la particularité de comporter des sujets mâles et des sujets femelles. Ces derniers produisent, de loin, les plus beaux épis. Ce sont eux que les pépiniéristes multiplient par éclats.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Attrait / Intérêt</titre>
        <alinea>végétation majestueuse. Légèreté des inflorescences.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Sol / Exposition</titre>
        <alinea>sols fertiles, bien drainés, en situation abritée et ensoleillée. Redoute l'excès d'humidité.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Culture</titre>
        <alinea>la multiplication s'opère par éclats de touffes au printemps. Compte tenu du développement de la touffe, les plantations se font généralement en "isolé". - Lorsque les froids surviennent, couper les chaumes à leur base et nettoyer les plantes, puis réunir les feuilles ensemble et les lier après avoir garni le centre de feuilles sèches. Le tout est recouvert d'une enveloppe de plastique qui rejettera les eaux loin du pied ; l'herbe de la Pampa est une plante qui craint plus l'humidité que le froid. - En mars-avril, cet abri est enlevé au moment du départ de la végétation et les vieilles feuilles sont coupées au ras du sol pour faire place aux nouvelles.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Utilisation</titre>
        <alinea>plante à isoler sur une pelouse ou dans un massif (prévoir un espace suffisant pour son développement). Dans de grands espaces, on peut planter par groupe de trois ou cinq. Les panaches, soyeux, coupés avant complète maturité et mis à sécher à l'ombre, la tête en bas, entrent dans la composition de superbes bouquets secs.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Herbe de la Pampa</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
      <photo_plante>
        <titre_photo>Gros minet</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/WEIGELIA_CADUC0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Weigela</taxon>
    <parent type="famille">Caprifoliaceae</parent>
    <contenu>
      <paragraphe>
        <titre>WEIGELIA CADUC</titre>
        <alinea>• Fleurit en mai-juillet Les weigelias sont des arbustes assez vigou- reux mais de taille moyenne (1,50 à 2,50 m) à port généralement évasé, à feuilles ovales. Fleurs réparties tout au long des rameaux, à partir de fin mai. La floraison se prolonge jusqu'en juillet, et des fleurs continuent souvent d'apparaître au cours de l'été. Les espèces types ne sont plus cultivées ; elles ont été remplacées par des variétés hybrides, à fleurs parfois blanches mais plus souvent roses ou rouges. En voici une sélection</alinea>
      </paragraphe>
    </contenu>
    <classeVilmorin type="arbuste" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/Dimorphotheca0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
    <description>
    <taxon type="genre">Osteospermum</taxon>
        <parent type = "famille">Asteraceae</parent>
        <contenu>
            <paragraphe>
                <titre>Dimorphothéca Annuelle</titre>
                <alinea>

                </alinea>
            </paragraphe>
        </contenu>

    <photos_plante>
        <photo_plante>
            <titre_photo>
                Dimorphothéca
            </titre_photo> 
            <fichier_photo_plante>
                p286_Dimorphotheca.jpg
            </fichier_photo_plante>
        </photo_plante>
    </photos_plante>
 
    <classeVilmorin type= "fleur"/>
    </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/Heliopsis1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
    <description>
        <taxon type="espece">Heliopsis scabra</taxon> 
        <parent type = "genre">Heliopsis</parent>
        <contenu>
            <paragraphe>
                <titre>Héliopside Vivace</titre>
                <alinea>
                Plante rustique, de 1 m de hauteur, à tiges lisses se ramifiant vers le sommet, à feuillage rude. Les fleurs, simples ou doubles, jaune d'or, en forme de soleil, à disque central conique proéminent, apparaissent de juillet à septembre.
                </alinea>
            </paragraphe>
            <paragraphe>
                <titre>Attrait intérêt</titre>
                <alinea>
                 floraison de fin d'été.   
                </alinea>
            </paragraphe>
            <paragraphe>
                <titre>Sol / exposition</titre>
                <alinea>
                sols profonds et substantiels, à exposition ensoleillée.    
                </alinea>
            </paragraphe>
            <paragraphe>
                <titre>Culture</titre>
                <alinea>
                multiplication par éclats de touffes à l'automne ou, mieux, au printemps. Plantez à 50 cm d'écartement. Arrosez copieusement en été.    
                </alinea>
            </paragraphe>
            <paragraphe>            
                <titre>Utilisation</titre>
                <alinea>
                identique à celle de l'hélénium :  massifs de vivaces, en association notamment avec des Asters.
                </alinea>
            </paragraphe>
         </contenu>
    
    <classeVilmorin type= "fleur"/>
        </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/PEUPLIER_CADUC0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Populus</taxon>
    <parent type="famille">Salicacées</parent>
    <contenu>
      <paragraphe>
        <titre>PEUPLIER CADUC</titre>
        <alinea>•Croissance rapide •Sols légers</alinea>
      </paragraphe>
    </contenu>
	<maladies>
      <maladie>
        <nom_maladie> Cloque dorée</nom_maladie>
        <enonce>Organe attaqué : feuilles.
Symptômes : des excroissances jaune d'or
en dessous et duveteuses au dessus se forment
sur les feuilles.
Conseil : affection spectaculaire mais sans
risque pour l'arbre
</enonce>
        <fichier_photo_maladie>??</fichier_photo_maladie>
      </maladie>
    </maladies>
    <classeVilmorin type="arbre" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/SETAIRE_A_GROSSE_BARBE1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Setaria macrochaeta</taxon>
    <parent type="genre">GRAMINEES ORNEMENTALES</parent>
    <contenu>
      <paragraphe>
        <titre>SETAIRE A GROSSE BARBE</titre>
        <alinea> Hauteur 1 m. Annuel. Gros épi dense, hérissi de barbes assez longues, formant comme ur goupillon, de couleur vert clair.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Culture</titre>
        <alinea>beaucoup d'espèces possèdent de; graines plumeuses, très menues, qui s'emmêlent entre elles et sont assez difficiles à séparer. - Semez de préférence celles-ci en terrine ou caissette, en avril, sous châssis, dans un mélange par tiers de terreau, sable et tourbe - Répartissez les graines le plus régulièrement possible et couvrez-les de 5 mm de mélange terreux. - Après la germination, qui est rapide, repiquez en pépinière et plantez en mai, en rangs espacés de 50 cm à 1 m, suivant la taille des espèces en cause. La distance sur la ligne, entre les plantes, doit être environ égale à la moitié de la hauteur qu'elles atteindront. - Semez les espèces à grosses graines non plumeuses en place ou, mieux, en pépinière fin avril et, dans ce dernier cas, plantez en mai, comme ci-dessus.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Utilisation</titre>
        <alinea>certaines espèces à port pittoresque et à développement assez important peuvent trouver place parmi les bordures d'arbustes et de fleurs vivaces ou être plantées en isolé sur pelouse (Pennisetum, Setaria). Toutefois, la destination principale des inflorescences de ces graminées est le séchage en vue de l'utilisation en bouquets secs, seules ou en association avec les acrocliniums, colo- quintes, boules azurées, immortelles, lunaires, maïs, physalis, statices et autres fleurs convenant à cet usage. Dans ce cas, la cueillette doit être faite lorsque les épis sont complètement développés mais avant que les petites fleurs qui les constituent ne s'ouvrent complètement ; coupez lorsque les premières de celles-ci (généralement celles de la base des épis) laissent sortir leurs étamines. Réunissez les tiges par petites bottes, sans les serrer, et entourez-les d'un cornet de papier pour les protéger de la poussière. Suspendez chaque botte tête en bas dans un local bien aéré, si possible obscur, jusqu'à complète dessiccation. Conservez ensuite en cartons jusqu'à l'utilisation.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Setaria macrochaeta</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/ERABLE_NEGUNDO1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Acer negundo</taxon>
    <parent type="genre">Acer</parent>
    <contenu>
      <paragraphe>
        <titre>ERABLE NEGUNDO</titre>
        <alinea> Hauteur 6 à 8 m. Arbre vigoureux et de crois- sance rapide, à rameaux verts et cassants, à feuilles composées de 5 à 7 folioles. Les variétés panachées, vigoureuses (4 à 5 m), sont plus largement répandues.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante />
    <classeVilmorin type="arbre" />
  </description>
</fiche>
