=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/plante_TextViz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  créé le ?? -->
<!--  modifié le 1 décembre 2011 -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="fiche">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="description">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="taxon">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeTaxon" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="parent">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeParent" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="contenu">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="paragraphe">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element minOccurs="0" name="titre" nillable="false" type="xsd:string"/>
                          <xsd:element name="alinea" nillable="false" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element minOccurs="0" name="maladies">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="maladie">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="nom_maladie" nillable="false" type="xsd:string"
                            maxOccurs="1"/>
                          <xsd:element name="enonce" nillable="false" type="xsd:string"/>
                          <xsd:element maxOccurs="1" minOccurs="0" name="photos_maladie">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element maxOccurs="unbounded" name="fichier_photo_maladie"
                                  type="xsd:string"/>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element maxOccurs="1" minOccurs="0" name="photos_plante">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element maxOccurs="unbounded" name="photo_plante">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="titre_photo" nillable="false" type="xsd:string"
                            maxOccurs="1"/>
                          <xsd:element name="fichier_photo_plante" type="xsd:string"/>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="classeVilmorin">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="type" type="typeClasseVilmorin" use="required"/>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="typeTaxon">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="genre"/>
      <xsd:enumeration value="espece"/>
      <xsd:enumeration value="variete"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="typeParent">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="famille"/>
      <xsd:enumeration value="genre"/>
      <xsd:enumeration value="espece"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="typeClasseVilmorin">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="arbre"/>
      <xsd:enumeration value="fleur"/>
      <xsd:enumeration value="arbuste"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/DAPHNE_MEZEREUM1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Daphne mezereum</taxon>
    <parent type="genre">Daphne</parent>
    <contenu>
      <paragraphe>
        <titre>DAPHNE MEZEREUM</titre>
        <alinea> Hauteur 0,50 m à 1 m. Le bois joli ou bois gentil se présente sous forme de rameaux dressés, peu ou pas ramifiés, garnis, fin février-mars, sur une partie de leur longueur, de manchons de fleurs rose lilacé délicieusement parfumées. Parfois, les fleurs s'épanouissent dès le début de l'hiver. Les feuilles, vert clair, se développent ensuite, surtout à l'extrémité des branches.  es fruits, d'un beau rouge vif comme des groseilles, sont extrêmement toxiques et, pour cette raison, il est recommandé de ne pas planter de bois joli là où il y a de jeunes enfants. Le bois joli prospère en toute bonne terre de jardin siliceuse et humifère, mais il ne craint ni le calcaire ni la sécheresse. Sa floraison parfumée et hivernale le désigne pour être à proximité de la maison. De reprise difficile, il est préférable de le planter en motte.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante />
    <classeVilmorin type="arbuste" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/Celosie11.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
    <description>
        <taxon type="variete">Aster nain 'Snow Sprite'Celosia argentea 'plumosa'</taxon>    
    <parent type = "espece">Aster nainCelosia argentea</parent>
        <contenu>
            <paragraphe>
                <titre> Célosie à panache</titre>
                <alinea> Célosie à panache varié,
Compacte, très ramifiée.
30               
                </alinea>
            </paragraphe>
            <paragraphe>
               <titre>Attrait / Intérêt</titre>
                <alinea>
                    
                </alinea>
            </paragraphe>
            <paragraphe>
               <titre>Sol / Exposition</titre>
                <alinea>
                    
                </alinea>
            </paragraphe>
        </contenu>

    <photos_plante>
        <photo_plante>
            <titre_photo>
                Célosie à panache
            </titre_photo> 
            <fichier_photo_plante>
                p267_Celosie_a_panache.jpg
            </fichier_photo_plante>
        </photo_plante>
    </photos_plante>
 
    <classeVilmorin type= "fleur"/>
        </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/GAURA_DE_LINDHEIMER_VIVACE0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Gaura Lindheimeri</taxon>
    <parent type="famille">Oenotheracées</parent>
    <contenu>
      <paragraphe>
        <titre>GAURA DE LINDHEIMER VIVACE</titre>
        <alinea />
      </paragraphe>
    </contenu>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/GLYCINE_TUBEREUSE_VIVACE0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Apios</taxon>
    <parent type="famille">Légumineuse</parent>
    <contenu>
      <paragraphe>
        <titre>GLYCINE TUBEREUSE VIVACE</titre>
        <alinea />
      </paragraphe>
    </contenu>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/FUSAIN_NAIN_A_BORDURES1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Euonymus japonicus 'Microphyllus'</taxon>
    <parent type="genre">Euonymus</parent>
    <contenu>
      <paragraphe>
        <titre>FUSAIN NAIN A BORDURES</titre>
        <alinea> Fusain à très petit feuillage, rappelant le Buis à bordures et utilisé de la même façon. Les fusains rampants sont essentiellement employés comme couvre-sol mais ils ont également leur place en isolé dans la rocaille. Palissés, ils garnissent aisément un petit muret ou un treillage.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
	<photos_plante>
      <photo_plante>
        <titre_photo>Fusain__Microphyllus_</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    
    <classeVilmorin type="arbuste" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/PAVOT_TULIPE1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Papaver glaucum</taxon>
    <parent type="genre">Pavot</parent>
    <contenu>
      <paragraphe>
        <titre>PAVOT TULIPE ESPÈCES ANNUELLES</titre>
        <alinea>Rouge brillant à 4 macules noires, fleur en coupe, 50 cm.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Culture</titre>
        <alinea>facile. - Semez de février à avril, en place de préférence, ou en pots et mettez en place sans diviser car les pavots annuels ne supportent pas le repiquage, - Eclaircissez à 20 cm d'écartement.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Attrait / Intérêt</titre>
        <alinea>très belles fleurs de grand diamètre aux jolis coloris.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Sol / Exposition</titre>
        <alinea>tous sols, même secs, à exposition ensoleillée.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Utilisation</titre>
        <alinea>ils s'intègrent parfaitement dans les massifs rustiques mais leur floraison extrêmement brillante est de courte durée et il faut prévoir d'autres plantes pour les remplacer en cours de saison.</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Pavot tulipe 'Lady Bird'</titre_photo>
        <fichier_photo_plante>??</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="fleur" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/OLEARIA_PERSISTANT0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="genre">Oléaria</taxon>
    <parent type="famille">Composées</parent>
    <contenu>
      <paragraphe>
        <titre>OLEARIA PERSISTANT</titre>
        <alinea>• Fleurit en mai-juin • Peu rustique</alinea>
      </paragraphe>
    </contenu>
    <classeVilmorin type="arbuste" />
  </description>
</fiche>

=== GuillaumePddn/TextAnnot/TextAnnot-WWW/WebContent/CorpusVilmorin/LIN_DE_NOUVELLE_ZELANDE_PERSISTANT1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plante_TextViz.xsd">
  <description>
    <taxon type="espece">Phormium tenax</taxon>
    <parent type="genre">Phormium</parent>
    <contenu>
      <paragraphe>
        <titre>LIN DE NOUVELLE ZELANDE PERSISTANT</titre>
        <alinea>• Résiste à-8/-10 Hauteur 0,5 à 1,20 m. Arbuste de climat doux de forme érigée très intéressant pour son feuillage décoratif en toutes saisons. Exposition ensoleillée et abritée, en tous sols.</alinea>
      </paragraphe>
      <paragraphe>
        <titre>Variétés</titre>
        <alinea>• 'Variegatum' feuillage vert, panaché de jaune • 'Purpureum' feuillage rouge pourpre • 'Bronze Baby' feuillage bronze</alinea>
      </paragraphe>
    </contenu>
    <maladies />
    <photos_plante>
      <photo_plante>
        <titre_photo>Lin de Nouvelle Zélande</titre_photo>
        <fichier_photo_plante>p463_Lin_de_Nouvelle_Zelande.jpg</fichier_photo_plante>
      </photo_plante>
    </photos_plante>
    <classeVilmorin type="arbuste" />
  </description>
</fiche>
